stages:
  - build
  - test
  - notify

docker_build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build .

docker-hadolint:
  image: hadolint/hadolint:latest-debian
  stage: test
  script:
    - mkdir -p reports
    - hadolint -f gitlab_codeclimate Dockerfile > reports/hadolint-$(md5sum Dockerfile | cut -d" " -f1).json
  artifacts:
    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    expire_in: 1 day
    when: always
    reports:
      codequality:
        - "reports/*"
    paths:
      - "reports/*"

shell_check:
  image: koalaman/shellcheck-alpine:stable
  stage: test
  before_script:
    - shellcheck --version
  script:
    - shellcheck src/**/*.sh

shfmt:
  image: mvdan/shfmt:v3.2.0-alpine
  stage: test
  before_script:
    - shfmt -version
  script:
    - shfmt -i 2 -ci -d src

comment_mr:
  image: ferrgo/gitlab-ci-notifier
  stage: notify
  variables:
    TOKEN: ${CICD_COMMENTER_TOKEN}
    COMMENT_MSG: "All passed to here"
  needs: ["docker_build","shell_check","shfmt"]
  script:
      - "./notifier.sh"
  allow_failure: true